language: python
python:
  - "3.6"
install:
  - pip install --index-url https://test.pypi.org/simple/ -r requirements-test.txt --extra-index-url https://pypi.org/simple/ -r requirements.txt
script: sh build.sh
